In [2]:
from sklearn.pipeline import make_pipeline
import numpy as np
from pycaret.classification import *
import pandas as pd

In [3]:
x_data = pd.read_csv('handwritten_digits_images.csv', sep=',').to_numpy()
y_data = pd.read_csv('handwritten_digits_labels.csv', sep=',').to_numpy()
data = np.concatenate([x_data, y_data], axis=1)
data = pd.DataFrame(data)

data = data.rename(columns={784: 'labels'})
exp1 = setup(data = data, target = 'labels')

Setup Succesfully Completed!

In [ ]:
best_model = compare_models(exclude = ["lightgbm", "xgboost", "gbc"])

IntProgress(value=0, description='Processing: ', max=146)

Initiated  . . . . . . . . . . . . . . . . . .                15:31:08
Status     . . . . . . . . . . . . . . . . . .    Fitting Fold 9 of 10
Estimator  . . . . . . . . . . . . . . . . . .     Logistic Regression
ETC        . . . . . . . . . . . . . . . . . .  3.74 Minutes Remaining

Empty DataFrame
Columns: [Model, Accuracy, AUC, Recall, Prec., F1, Kappa, MCC, TT (Sec)]
Index: []

In [ ]:
tune_best_model = tune_model(best_model)